services:

#BACK STUFF

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data_db:/data/db
  
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
  backend:
    build: 
      context: ./todo-backend
      dockerfile: Dockerfile
    image: todo-backend
    container_name: todo-backend   
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
      - REDIS_URL=redis://redis:6379
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - redis
      - mongo

#FRONT STUFF  
  nginx-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    image: nginx-frontend-todo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy-frontend
    depends_on:
      - backend
volumes:
  mongo_data_db:
